.Dd June 9, 2010
.Dt TRANSMISSION-OG-SHOW 1
.Os
.Sh NAME
.Nm transmission-og-show
.Nd command-line utility to show .torrent file metadata
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl h
.Op Fl m
.Op Fl s
.Op Ar torrentfile
.Ek
.Sh DESCRIPTION
.Nm
shows BitTorrent .torrent file metadata
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h Fl -help
Show a short help page and exit.
.It Fl m Fl -magnet
Show a magnet link for the specified .torrent file
.It Fl s Fl -scrape
Ask the torrent's trackers how many peers are in the torrent's swarm
.El
.Sh AUTHORS
.An -nosplit
.An Charles Kerr
and
.An Mike Gelfand .
.Sh SEE ALSO
.Xr transmission-og-create 1 ,
.Xr transmission-og-daemon 1 ,
.Xr transmission-og-edit 1 ,
.Xr transmission-og-gtk 1 ,
.Xr transmission-og-qt 1 ,
.Xr transmission-og-remote 1 ,
.Xr transmission-og-show 1
.Pp
https://github.com/stefantalpalaru/transmission-og
